title: Your awesome title
author: GitHub User
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
hi I am ychio1 I am interested in codeing
# social links
github_username: ychio

show_excerpts: true # set to false to remove excerpts on the homepage
